# Generated by Django 5.0.6 on 2024-05-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BRAZIL', 'Brasil'), ('GB', 'Reino Unido'), ('DE', 'Alemanha'), ('IL', 'Israel')], max_length=100, null=True),
        ),
    ]
